### PR TITLE
anish/AEM-1911 Optimize images

### PR DESCRIPTION
**Pull request by kylerbeetun**

### CODE REVIEW

**Comment by johvet** [comment]
LGTM

**Comment by ziggythehamster** [comment]
image

image

The Windows tile images are sized incorrectly.

**Comment by ziggythehamster** [comment]
mstile 144x144 is correct. The others aren't though.

**Comment by kylerbeetun** [comment]
Yes, i guess that's how it's supposed to be. These are auto-generated favicons

**Comment by ziggythehamster** [comment]
Actually, MSDN gives different numbers for each size: https://msdn.microsoft.com/en-us/library/dn455106(v=vs.85).aspx

Let me double-check those then :)

**Comment by kylerbeetun** [comment]
i use realfavicongenerator.net btw :)

**Comment by ziggythehamster** [comment]
* 70x70: OK
* 144x144: this is the msapplication-TileImage, which I guess is the correct size (it's not documented in the same place)
* 150x150: OK
* 310x150: pixel size is correct, but the image you provided is square. your image should be rectangular.
* 310x310: OK

**Comment by ziggythehamster** [comment]
Also, once we get these perfect, we should probably ensure the real ART19 website has the correct favicon stuff going on :)

**Comment by ziggythehamster** [comment]
Also, don't forget to pick a tile color from this list: https://colorlib.com/etc/metro-colors/

`#da532c` is orange

**Comment by ziggythehamster** [comment]
(and also don't forget to set the tile color in both the browserconfig.xml and index.html)

**Comment by kylerbeetun** [comment]
@ziggythehamster Updated, please re-review.

**Comment by ziggythehamster** [comment]
The MS tiles should fill all of the available space. The GitHub preview is showing that there's a transparent border and some of them aren't centered.

**Comment by ziggythehamster** [comment]
The original file sizes were correct (see MSDN), you just needed to have the image fill up the available space.

**Comment by kylerbeetun** [comment]
shit.. on it again

**Comment by ziggythehamster** [comment]
This looks good now. 👍 

That said, I wonder if maybe it's a bad idea to drop our logos into an open source project, since someone might think that our images are licensed under the Apache license because we don't say otherwise. Let's figure out a solution to that via Slack :).

**Comment by kylerbeetun** [comment]
That's true @ziggythehamster. i will let you discuss this with johannes or josh.

**Pull request merged**
